# Generated by Django 4.0.3 on 2022-04-11 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibit_id', models.AutoField(primary_key=True, serialize=False)),
                ('exhibit_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('featured_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('revealed', models.BooleanField(blank=True, default=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Exhibits',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='images/profiles/user-default.png', null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('upload', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('exhibit_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pics', to='studios.exhibit')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='exhibit',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibits', to='studios.profile'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='tags',
            field=models.ManyToManyField(to='studios.tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('exhibit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='studios.exhibit')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
