# Generated by Django 4.0.3 on 2022-04-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(blank=True, default='art/default.png', null=True, upload_to='images/art'),
        ),
    ]
