# Generated by Django 4.0.3 on 2022-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(blank=True, default='art/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='images/profiles/'),
        ),
    ]
