# Generated by Django 4.0.3 on 2022-04-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0010_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/art'),
        ),
    ]
